spring:
  application:
    name: webTaxi

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/webTaxiDb
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 3000

token:
  remaining-time: 300000
  remaining-refresh-time: 864000000

rabbitmq:
  exchange: web.taxi.exchange
  notice-driver-routing-key: notice.driver.key
  notice-driver-paid-price-routing-key: notice.driver.paid.price.key
